### ISSUE TITLE
Ambitious mission statement 

### ISSUE THREAD

**Issue by kdungs** [lhcb/starterkit#14]
We should define a clear mission statement like "Bringing LHCb software to the 21st century" and include it in the website's header.

See [Culture & Empire chapter 2](http://content.cultureandempire.com/chapter2.html#strong-mission) for reference.

**Comment by kdungs** [comment]
Actually,

> Starterkit is a group of physicists who want to improve the working lives of young researchers working on the LHCb experiment.

is a pretty good start.

**Comment by betatim** [comment]
Make mission statements great again! 😀

**Comment by kdungs** [comment]
The reason I closed this is because the above has become the de-facto statement which is on the website etc.
It could still be worth reconsidering e.g. w.r.t. making it a CERN-wide effort ;)
