### ISSUE TITLE
Grammtical mistake/unclear wording in "Changes to data flow in Run2"

### ISSUE THREAD

**Issue by KonstantinSchubert** [lhcb/starterkit#26]
The text to the section "Changes to data flow in Run2" contains the following sentence:

That is to say, any tracks or detector responses that don't form part of the decay that the trigger lines uses to evaluate its selection is thrown away. 

"Trigger lines" is plural, but the following verb "uses" is singular. Unfortunately I cannot correct this because I really don't know what the right answer is. 

Are tracks really thrown away until they contribute to trigger any of the L0, Hlt1, oder Hlt2 lines? Doesn't that throw away a lot of good TIS events?

**Comment by apuignav** [comment]
Something missing in the issue?

**Comment by KonstantinSchubert** [comment]
Yes, I had pressed Ctrl+Enter too fast, habit from slack..

**Comment by kdungs** [comment]
Would you mind migrating this to lhcb/first-analysis-steps? Having it in that repository would make referencing it easier plus it would draw more attention to the issue and help resolving it. Feel feel to close this one afterwards. :)

**Comment by alexpearce** [comment]
Migrated to lhcb/first-analysis-steps#186.
