### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by kdungs** [lhcb/starterkit#27]
<img width="393" alt="screen shot 2016-09-19 at 22 18 44" src="https://cloud.githubusercontent.com/assets/891877/18647615/0f9309a4-7eb7-11e6-8120-9c6d69ca244b.png">

Just discovered that the beautiful design doesn't do so well on mobile. WDYT about going single column for mobile?

**Comment by alexpearce** [comment]
Turns out I have a 4-month-old branch locally that does exactly this.

<img width="399" alt="Mobile-first, baby" src="https://cloud.githubusercontent.com/assets/540853/18661743/9ffaf8f2-7f17-11e6-89b9-f5ebe29ecbde.png">

**Comment by alexpearce** [comment]
Fixed by #28.

**Comment by kdungs** [comment]
Whoop whoop! 🍾
