### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by kdungs** [lhcb/starterkit#3]
Set up Travis to build the page as a rudimentary check.

**Comment by alexpearce** [comment]
I can look in to this using the [`.travis.yml` in the first-analysis-steps repo](https://github.com/lhcb/first-analysis-steps/blob/826b492c91b6b2c36a16487f80704ce5c7c34057/.travis.yml). Only thing I'm unsure about is where to get the `env-global-secure` key from. I think it was @ibab who set this up.

**Comment by kdungs** [comment]
We don't need this for deployment as GitHub takes care of running Jekyll.

The idea behind this was to have Jekyll run also on every PR to see that the site builds at least. So afaik there's no need for secrets ;)
