### ISSUE TITLE
Summary of Spring 2017 Impactkit

### ISSUE THREAD

**Issue by alexpearce** [lhcb/starterkit#36]
A huge thanks and congratulations to Svende and Lorenzo (not on GitHub ‼️❓) for organising the [most recent Impactkit](https://indico.cern.ch/event/624551/)! I think it went pretty darn well 😄 

The final task is to write a summary page, saying what happened, how things went, adding a few nice photos, and thanking everyone involved. The [page for the last Starterkit](https://lhcb.github.io/starterkit/starterkit/2016/11/28/starterkit-autumn-2016.html) should give us an idea.

**Comment by lcapriot** [comment]
I am here! :) Thank you for this message! I have a few photos but I am currently (officially) learning statistics in Ischia so I won't be available till next week. I suppose you and @lbel should have the rest of the photos we took?

**Comment by apuignav** [comment]
I have tons of photos 📷

**Comment by chrisburr** [comment]
Completed with #37
