### ISSUE TITLE
Tmux / screen in starterkit

### ISSUE THREAD

**Issue by atrisovic** [lhcb/starterkit#38]
Hi!

This is just an idea to add to the LHCb starterkit.
Tmux / screen are very handy tools for running scripts, and (searching for a few minutes this repo) I don't think they are now included, but probably should be mentioned.
Both are installed on lxplus.
PS: I can help to create an example and description.

Cheers,
Ana

**Comment by alexpearce** [comment]
We do have [something on screen in analysis-essentials](https://github.com/lhcb/analysis-essentials/blob/1bb95b97944e9be6b045150954ce4573baec1f99/shell/screen.md), though that repo is quite unloved 😢

**Comment by atrisovic** [comment]
Haha, it looks really helpful! 
I am not sure if it should be added on the website, maybe not if it's already in the prerequisites :)
