### ISSUE TITLE
Projects for 2019 Impactkit

### ISSUE THREAD

**Issue by chrisburr** [lhcb/starterkit#47]
We should start making notes of project ideas for the next Impactkit:
 - Outreach ideas (especially in preparation for the open days in September 2019)

As I can't assign you: @andriiusachov

**Comment by mesmith75** [comment]
It may exist already but it would be great if someone could make an equivalent of the lumi tuple for MC. i.e. something that saves the no. of events processed and maybe some other useful info (essentially everything that turns up in the metadata)
